# Generated by Django 2.2.7 on 2019-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_nursinginstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
