# Generated by Django 2.2.7 on 2019-11-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
