# Generated by Django 2.2.7 on 2019-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_r3'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
