# Generated by Django 2.2.7 on 2019-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_rx2"),
    ]

    operations = [
        migrations.CreateModel(
            name="RX3",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r1", models.BigIntegerField()),
            ],
        ),
    ]
