# Generated by Django 2.2.7 on 2019-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rx3'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx3',
            name='r2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
