# Generated by Django 2.2.7 on 2019-12-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_auto_20191204_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rxxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
                ('r2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rxxx_r2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
