# Generated by Django 2.2.7 on 2019-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_rxxx"),
    ]

    operations = [
        migrations.AddField(
            model_name="rxxx",
            name="r3",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
