# Generated by Django 2.2.7 on 2019-12-11 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0020_rxxx_r3"),
    ]

    operations = [
        migrations.CreateModel(
            name="XT1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xt1_r1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
